const fs = require('fs');

// ── src/components/Toast.jsx
fs.writeFileSync('src/components/Toast.jsx', [
  "import { useEffect } from 'react';",
  "export default function Toast({ msg, type='success', onDone }) {",
  "  const ic={success:'check-circle',info:'info-circle',warning:'exclamation-triangle',error:'times-circle'};",
  "  const bg={success:'#D1FAE5',info:'#DBEAFE',warning:'#FEF3C7',error:'#FFE4E6'};",
  "  const tc={success:'#065F46',info:'#1E40AF',warning:'#92400E',error:'#9F1239'};",
  "  useEffect(()=>{const t=setTimeout(onDone,3500);return()=>clearTimeout(t)},[]);",
  "  return (",
  "    <div className='si' style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:14,padding:'12px 16px',boxShadow:'0 12px 40px rgba(0,0,0,.12)',display:'flex',alignItems:'center',gap:11,minWidth:270,maxWidth:340}}>",
  "      <div style={{width:30,height:30,borderRadius:8,background:bg[type],color:tc[type],display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0,fontSize:13}}><i className={'fas fa-'+ic[type]}/></div>",
  "      <span style={{fontSize:13}}>{msg}</span>",
  "    </div>",
  "  );",
  "}"
].join('\n'));

// ── src/components/ToastStack.jsx
fs.writeFileSync('src/components/ToastStack.jsx', [
  "import { useState, useCallback } from 'react';",
  "import Toast from './Toast';",
  "let _addToast = null;",
  "export const toast = (msg, type='success') => _addToast && _addToast(msg, type);",
  "export default function ToastStack() {",
  "  const [toasts, setToasts] = useState([]);",
  "  _addToast = useCallback((msg, type) => {",
  "    const id = Date.now();",
  "    setToasts(p => [...p, { id, msg, type }]);",
  "  }, []);",
  "  const remove = id => setToasts(p => p.filter(t => t.id !== id));",
  "  return (",
  "    <div style={{position:'fixed',top:18,right:18,zIndex:9999,display:'flex',flexDirection:'column',gap:9}}>",
  "      {toasts.map(t => <Toast key={t.id} msg={t.msg} type={t.type} onDone={()=>remove(t.id)}/>)}",
  "    </div>",
  "  );",
  "}"
].join('\n'));

// ── src/components/Modal.jsx
fs.writeFileSync('src/components/Modal.jsx', [
  "export default function Modal({ open, onClose, title, children, width=480 }) {",
  "  if (!open) return null;",
  "  return (",
  "    <div onClick={e=>{if(e.target===e.currentTarget)onClose()}} style={{position:'fixed',inset:0,background:'rgba(6,14,26,.8)',backdropFilter:'blur(12px)',zIndex:2000,display:'flex',alignItems:'center',justifyContent:'center',padding:20}}>",
  "      <div className='si' style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:20,padding:32,width:'100%',maxWidth:width,boxShadow:'0 24px 64px rgba(0,0,0,.2)',maxHeight:'90vh',overflowY:'auto',position:'relative'}}>",
  "        <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:22}}>",
  "          <div style={{fontFamily:'Syne,sans-serif',fontSize:18,fontWeight:700}}>{title}</div>",
  "          <button onClick={onClose} style={{background:'var(--surf2)',border:'none',borderRadius:8,width:32,height:32,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',color:'var(--txt2)',fontSize:14}}>✕</button>",
  "        </div>",
  "        {children}",
  "      </div>",
  "    </div>",
  "  );",
  "}"
].join('\n'));

// ── src/components/Chatbot.jsx
fs.writeFileSync('src/components/Chatbot.jsx', [
  "import { useState, useRef, useEffect } from 'react';",
  "const tg = 'linear-gradient(135deg,#0D9B82,#1DBEA0)';",
  "const REPLIES = {",
  "  'queue status': 'You are currently at position #3. Estimated wait: ~12 minutes. Dr. Sarah Smith is seeing patient #32.',",
  "  'book': 'Go to Find Doctors, select a specialist and available slot. I can guide you!',",
  "  'prescription': 'Your Amoxicillin (500mg) expires in 5 days. Want me to send a refill request?',",
  "  'symptom': 'Describe your symptoms and I will help assess severity. Note: not a medical diagnosis.',",
  "  'hello': 'Hello! I am your MEDIQUEUE AI assistant. How can I help you today?',",
  "  'hi': 'Hi there! How can I assist you today?',",
  "  'wait': 'Average wait time today is 12 minutes. The queue has 5 patients ahead.',",
  "  'cancel': 'To cancel an appointment, go to Appointments panel and click Cancel on the appointment.',",
  "};",
  "const getReply = (msg) => {",
  "  const lower = msg.toLowerCase();",
  "  for (const [key, val] of Object.entries(REPLIES)) {",
  "    if (lower.includes(key)) return val;",
  "  }",
  "  return 'I understand your concern. Let me help — could you provide more details so I can assist you better?';",
  "};",
  "export default function Chatbot() {",
  "  const [open, setOpen] = useState(false);",
  "  const [msgs, setMsgs] = useState([{ who:'bot', text:'👋 Hello! I am your AI health assistant. I can help you book appointments, check queue status, or answer health questions.' }]);",
  "  const [input, setInput] = useState('');",
  "  const [typing, setTyping] = useState(false);",
  "  const ref = useRef();",
  "  useEffect(() => { if(ref.current) ref.current.scrollTop = ref.current.scrollHeight; }, [msgs]);",
  "  const send = (txt) => {",
  "    const m = txt || input.trim();",
  "    if (!m) return;",
  "    setMsgs(p => [...p, { who:'user', text:m }]);",
  "    setInput('');",
  "    setTyping(true);",
  "    setTimeout(() => {",
  "      setTyping(false);",
  "      setMsgs(p => [...p, { who:'bot', text:getReply(m) }]);",
  "    }, 800);",
  "  };",
  "  return (",
  "    <>",
  "      <div onClick={()=>setOpen(v=>!v)} style={{position:'fixed',bottom:24,right:24,width:54,height:54,background:tg,borderRadius:15,display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer',boxShadow:'0 8px 24px rgba(13,155,130,.4)',zIndex:998,transition:'all .2s'}}>",
  "        <i className={'fas fa-'+(open?'times':'comment-medical')} style={{color:'#fff',fontSize:20}}/>",
  "      </div>",
  "      {open && (",
  "        <div className='si' style={{position:'fixed',bottom:90,right:24,width:340,height:500,background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:20,display:'flex',flexDirection:'column',zIndex:999,boxShadow:'0 24px 64px rgba(0,0,0,.18)',overflow:'hidden'}}>",
  "          <div style={{padding:'14px 16px',background:tg,display:'flex',alignItems:'center',justifyContent:'space-between',flexShrink:0}}>",
  "            <div>",
  "              <div style={{fontWeight:700,fontSize:14,color:'#fff'}}>MEDIQUEUE AI</div>",
  "              <div style={{fontSize:11,color:'rgba(255,255,255,.8)',display:'flex',alignItems:'center',gap:5}}><span style={{width:5,height:5,background:'#4ADE80',borderRadius:'50%',animation:'pulse 1.5s infinite'}}/>Online 24/7</div>",
  "            </div>",
  "            <button onClick={()=>setOpen(false)} style={{background:'rgba(255,255,255,.15)',border:'none',borderRadius:8,width:28,height:28,cursor:'pointer',color:'#fff',fontSize:12}}>✕</button>",
  "          </div>",
  "          <div ref={ref} style={{flex:1,overflowY:'auto',padding:12,display:'flex',flexDirection:'column',gap:8}}>",
  "            {msgs.map((m,i)=>(",
  "              <div key={i} style={{display:'flex',justifyContent:m.who==='user'?'flex-end':'flex-start'}}>",
  "                <div style={{maxWidth:'80%',padding:'8px 12px',borderRadius:m.who==='user'?'12px 12px 3px 12px':'12px 12px 12px 3px',background:m.who==='user'?tg:'var(--surf2)',color:m.who==='user'?'#fff':'var(--txt)',fontSize:12,lineHeight:1.55}}>{m.text}</div>",
  "              </div>",
  "            ))}",
  "            {typing && <div style={{display:'flex',justifyContent:'flex-start'}}><div style={{padding:'8px 14px',borderRadius:'12px 12px 12px 3px',background:'var(--surf2)',fontSize:12,color:'var(--txt3)'}}>Typing...</div></div>}",
  "          </div>",
  "          <div style={{display:'flex',gap:6,flexWrap:'wrap',padding:'0 10px 8px'}}>",
  "            {['Queue status','Book appointment','Refill prescription','Symptom check'].map(q=>(",
  "              <span key={q} onClick={()=>send(q)} style={{background:'var(--tealXL)',color:'var(--tealDk)',border:'1px solid rgba(13,155,130,.2)',borderRadius:99,padding:'3px 10px',fontSize:11,cursor:'pointer'}}>{q}</span>",
  "            ))}",
  "          </div>",
  "          <div style={{display:'flex',gap:6,padding:'10px',borderTop:'1px solid var(--bdr)',flexShrink:0}}>",
  "            <input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder='Type a message...' style={{flex:1,background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:8,padding:'8px 11px',fontFamily:'DM Sans,sans-serif',fontSize:12,color:'var(--txt)',outline:'none'}}/>",
  "            <button onClick={()=>send()} style={{padding:'8px 13px',background:tg,color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontSize:12}}><i className='fas fa-paper-plane'/></button>",
  "          </div>",
  "        </div>",
  "      )}",
  "    </>",
  "  );",
  "}"
].join('\n'));

// ── src/pages/panels/AppointmentsPanel.jsx
fs.mkdirSync('src/pages/panels', { recursive: true });
fs.writeFileSync('src/pages/panels/AppointmentsPanel.jsx', [
  "import { useState, useEffect } from 'react';",
  "import { appointmentAPI, doctorAPI } from '../../services/api';",
  "import Modal from '../../components/Modal';",
  "import { toast } from '../../components/ToastStack';",
  "const tg = 'linear-gradient(135deg,#0D9B82,#1DBEA0)';",
  "const statusColor = { confirmed:{bg:'#D1FAE5',c:'#065F46'}, completed:{bg:'#E6F7F4',c:'#0A7A67'}, cancelled:{bg:'#FFE4E6',c:'#9F1239'}, pending:{bg:'#FEF3C7',c:'#92400E'}, no_show:{bg:'#FFE4E6',c:'#9F1239'} };",
  "",
  "export default function AppointmentsPanel({ role }) {",
  "  const [appts, setAppts] = useState([]);",
  "  const [doctors, setDoctors] = useState([]);",
  "  const [loading, setLoading] = useState(true);",
  "  const [modal, setModal] = useState(false);",
  "  const [form, setForm] = useState({ doctor_id:'', date:'', time:'', type:'in_person', chief_complaint:'' });",
  "  const [slots, setSlots] = useState([]);",
  "  const [booking, setBooking] = useState(false);",
  "",
  "  const load = async () => {",
  "    try {",
  "      const r = await appointmentAPI.getAll();",
  "      setAppts(r.data.appointments || []);",
  "      if (role === 'patient') {",
  "        const d = await doctorAPI.getAll();",
  "        setDoctors(d.data.doctors || []);",
  "      }",
  "    } catch(e) { toast('Failed to load appointments','error'); }",
  "    finally { setLoading(false); }",
  "  };",
  "",
  "  useEffect(() => { load(); }, []);",
  "",
  "  const loadSlots = async (doctorId, date) => {",
  "    if (!doctorId || !date) return;",
  "    try {",
  "      const r = await doctorAPI.getAvailability(doctorId, date);",
  "      setSlots(r.data.slots || []);",
  "    } catch(e) { setSlots([]); }",
  "  };",
  "",
  "  const book = async () => {",
  "    if (!form.doctor_id || !form.date || !form.time) { toast('Please fill all fields','warning'); return; }",
  "    setBooking(true);",
  "    try {",
  "      const dt = form.date + 'T' + form.time + ':00';",
  "      await appointmentAPI.book({ doctor_id: form.doctor_id, appointment_time: dt, type: form.type, chief_complaint: form.chief_complaint });",
  "      toast('Appointment booked successfully!','success');",
  "      setModal(false);",
  "      setForm({ doctor_id:'', date:'', time:'', type:'in_person', chief_complaint:'' });",
  "      load();",
  "    } catch(e) { toast(e.response?.data?.message || 'Booking failed','error'); }",
  "    finally { setBooking(false); }",
  "  };",
  "",
  "  const cancel = async (id) => {",
  "    if (!window.confirm('Cancel this appointment?')) return;",
  "    try {",
  "      await appointmentAPI.cancel(id);",
  "      toast('Appointment cancelled','info');",
  "      load();",
  "    } catch(e) { toast('Failed to cancel','error'); }",
  "  };",
  "",
  "  if (loading) return <div style={{padding:40,color:'var(--txt2)',fontSize:14}}>Loading appointments...</div>;",
  "",
  "  return (",
  "    <div className='fu'>",
  "      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:20}}>",
  "        <div style={{fontFamily:'Syne,sans-serif',fontSize:16,fontWeight:700}}>",
  "          {role==='doctor'?\"Today's Schedule\":'My Appointments'}",
  "          <span style={{marginLeft:10,fontSize:12,padding:'3px 10px',borderRadius:99,background:'var(--tealXL)',color:'var(--tealDk)',fontWeight:700}}>{appts.length} total</span>",
  "        </div>",
  "        {role==='patient' && <button onClick={()=>setModal(true)} style={{padding:'9px 18px',background:tg,color:'#fff',border:'none',borderRadius:10,fontFamily:'DM Sans,sans-serif',fontSize:13,fontWeight:700,cursor:'pointer',display:'flex',alignItems:'center',gap:7}}><i className='fas fa-plus'/>Book Appointment</button>}",
  "      </div>",
  "",
  "      <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,overflow:'hidden'}}>",
  "        {appts.length === 0 ? (",
  "          <div style={{textAlign:'center',padding:'48px 0',color:'var(--txt3)',fontSize:14}}>",
  "            <i className='fas fa-calendar' style={{fontSize:40,display:'block',marginBottom:12}}/> No appointments yet",
  "            {role==='patient'&&<button onClick={()=>setModal(true)} style={{marginTop:14,padding:'9px 18px',background:tg,color:'#fff',border:'none',borderRadius:10,fontFamily:'DM Sans,sans-serif',fontSize:13,fontWeight:700,cursor:'pointer'}}>Book Your First Appointment</button>}",
  "          </div>",
  "        ) : (",
  "          <table style={{width:'100%',borderCollapse:'collapse'}}>",
  "            <thead><tr style={{borderBottom:'1px solid var(--bdr)'}}>",
  "              {['Date & Time', role==='doctor'?'Patient':'Doctor', 'Speciality','Type','Status','Action'].map(h=>(",
  "                <th key={h} style={{fontSize:11,fontWeight:700,letterSpacing:.7,textTransform:'uppercase',color:'var(--txt3)',padding:'12px 14px',textAlign:'left'}}>{h}</th>",
  "              ))}",
  "            </tr></thead>",
  "            <tbody>",
  "              {appts.map((a,i)=>(",
  "                <tr key={i} style={{borderBottom:'1px solid var(--bdr)',transition:'.15s'}} onMouseEnter={e=>e.currentTarget.style.background='var(--surf2)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>",
  "                  <td style={{padding:'13px 14px',fontSize:13,fontWeight:600}}>{new Date(a.appointment_time).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</td>",
  "                  <td style={{padding:'13px 14px',fontSize:13}}>{role==='doctor'?a.patient_name:a.doctor_name||'—'}</td>",
  "                  <td style={{padding:'13px 14px',fontSize:12,color:'var(--txt2)'}}>{a.speciality||'—'}</td>",
  "                  <td style={{padding:'13px 14px'}}><span style={{fontSize:11,padding:'3px 9px',borderRadius:99,fontWeight:700,background:a.type==='telehealth'?'#EDE9FE':'#DBEAFE',color:a.type==='telehealth'?'#5B21B6':'#1E40AF'}}>{a.type}</span></td>",
  "                  <td style={{padding:'13px 14px'}}><span style={{fontSize:11,padding:'3px 9px',borderRadius:99,fontWeight:700,...(statusColor[a.status]||{bg:'#F1F5F9',c:'#64748B'})}}>{a.status}</span></td>",
  "                  <td style={{padding:'13px 14px'}}>",
  "                    {role==='patient' && a.status==='confirmed' && (",
  "                      <button onClick={()=>cancel(a.id)} style={{padding:'5px 12px',background:'#FFE4E6',color:'#9F1239',border:'none',borderRadius:7,fontSize:12,fontWeight:600,cursor:'pointer'}}>Cancel</button>",
  "                    )}",
  "                  </td>",
  "                </tr>",
  "              ))}",
  "            </tbody>",
  "          </table>",
  "        )}",
  "      </div>",
  "",
  "      <Modal open={modal} onClose={()=>setModal(false)} title='Book New Appointment'>",
  "        <div style={{marginBottom:14}}>",
  "          <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:5,textTransform:'uppercase',letterSpacing:.4}}>Select Doctor</label>",
  "          <select value={form.doctor_id} onChange={e=>{setForm(f=>({...f,doctor_id:e.target.value,time:''}));loadSlots(e.target.value,form.date);}} style={{width:'100%',padding:'11px 14px',background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:10,fontSize:13,color:'var(--txt)',outline:'none'}}>",
  "            <option value=''>-- Choose a doctor --</option>",
  "            {doctors.map(d=><option key={d.id} value={d.id}>{d.name} — {d.speciality} (₹{d.consultation_fee})</option>)}",
  "          </select>",
  "        </div>",
  "        <div style={{marginBottom:14}}>",
  "          <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:5,textTransform:'uppercase',letterSpacing:.4}}>Date</label>",
  "          <input type='date' value={form.date} min={new Date().toISOString().slice(0,10)} onChange={e=>{setForm(f=>({...f,date:e.target.value,time:''}));loadSlots(form.doctor_id,e.target.value);}} style={{width:'100%',padding:'11px 14px',background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:10,fontSize:13,color:'var(--txt)',outline:'none'}}/>",
  "        </div>",
  "        {slots.length > 0 && (",
  "          <div style={{marginBottom:14}}>",
  "            <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:8,textTransform:'uppercase',letterSpacing:.4}}>Available Slots</label>",
  "            <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:7}}>",
  "              {slots.filter(s=>s.available).map(s=>(",
  "                <button key={s.time} onClick={()=>setForm(f=>({...f,time:s.time}))} style={{padding:'8px 4px',border:'1.5px solid',borderRadius:9,fontSize:12,fontWeight:600,cursor:'pointer',transition:'all .15s',borderColor:form.time===s.time?'var(--teal)':'var(--bdr)',background:form.time===s.time?'var(--tealXL)':'transparent',color:form.time===s.time?'var(--teal)':'var(--txt2)'}}>{s.time}</button>",
  "              ))}",
  "            </div>",
  "          </div>",
  "        )}",
  "        <div style={{marginBottom:14}}>",
  "          <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:5,textTransform:'uppercase',letterSpacing:.4}}>Type</label>",
  "          <select value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value}))} style={{width:'100%',padding:'11px 14px',background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:10,fontSize:13,color:'var(--txt)',outline:'none'}}>",
  "            <option value='in_person'>In-Person</option>",
  "            <option value='telehealth'>Telehealth</option>",
  "          </select>",
  "        </div>",
  "        <div style={{marginBottom:22}}>",
  "          <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:5,textTransform:'uppercase',letterSpacing:.4}}>Chief Complaint</label>",
  "          <textarea value={form.chief_complaint} onChange={e=>setForm(f=>({...f,chief_complaint:e.target.value}))} placeholder='Briefly describe your symptoms or reason for visit...' rows={3} style={{width:'100%',padding:'11px 14px',background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:10,fontSize:13,color:'var(--txt)',outline:'none',resize:'vertical'}}/>",
  "        </div>",
  "        <button onClick={book} disabled={booking} style={{width:'100%',padding:'13px',background:tg,color:'#fff',border:'none',borderRadius:10,fontFamily:'DM Sans,sans-serif',fontSize:14,fontWeight:700,cursor:'pointer',boxShadow:'0 4px 14px rgba(13,155,130,.3)'}}>",
  "          {booking?'Booking...':'Confirm Appointment'}",
  "        </button>",
  "      </Modal>",
  "    </div>",
  "  );",
  "}"
].join('\n'));

// ── src/pages/panels/QueuePanel.jsx
fs.writeFileSync('src/pages/panels/QueuePanel.jsx', [
  "import { useState, useEffect, useCallback } from 'react';",
  "import { queueAPI, appointmentAPI } from '../../services/api';",
  "import { joinQueueRoom, onQueueUpdated, offQueueUpdated, emitCallNext } from '../../services/socket';",
  "import { toast } from '../../components/ToastStack';",
  "const tg = 'linear-gradient(135deg,#0D9B82,#1DBEA0)';",
  "",
  "export default function QueuePanel({ role }) {",
  "  const [queue, setQueue] = useState([]);",
  "  const [myEntry, setMyEntry] = useState(null);",
  "  const [appts, setAppts] = useState([]);",
  "  const [doctorId, setDoctorId] = useState('');",
  "  const [loading, setLoading] = useState(false);",
  "  const [joining, setJoining] = useState(false);",
  "",
  "  const loadQueue = useCallback(async (dId) => {",
  "    if (!dId) return;",
  "    setLoading(true);",
  "    try {",
  "      const r = await queueAPI.getStatus(dId);",
  "      setQueue(r.data.queue || []);",
  "    } catch(e) { console.error(e); }",
  "    finally { setLoading(false); }",
  "  }, []);",
  "",
  "  useEffect(() => {",
  "    if (role === 'patient') {",
  "      appointmentAPI.getAll().then(r => {",
  "        const confirmed = (r.data.appointments||[]).filter(a=>a.status==='confirmed');",
  "        setAppts(confirmed);",
  "      });",
  "    }",
  "  }, [role]);",
  "",
  "  useEffect(() => {",
  "    if (!doctorId) return;",
  "    joinQueueRoom(doctorId);",
  "    loadQueue(doctorId);",
  "    onQueueUpdated((data) => {",
  "      toast('Queue updated: Token ' + data.currentToken + ' called','info');",
  "      loadQueue(doctorId);",
  "    });",
  "    return () => offQueueUpdated();",
  "  }, [doctorId, loadQueue]);",
  "",
  "  const joinQueue = async (apptId, dId) => {",
  "    setJoining(true);",
  "    try {",
  "      const r = await queueAPI.join(apptId);",
  "      setMyEntry(r.data.queueEntry);",
  "      setDoctorId(dId);",
  "      toast('Joined queue! Token: ' + r.data.queueEntry.token_number,'success');",
  "      loadQueue(dId);",
  "    } catch(e) { toast(e.response?.data?.message||'Failed to join queue','error'); }",
  "    finally { setJoining(false); }",
  "  };",
  "",
  "  const callNext = async () => {",
  "    try {",
  "      const r = await queueAPI.callNext(doctorId);",
  "      if (r.data.next) {",
  "        emitCallNext({ doctorId, tokenNumber: r.data.next.token_number, patientName: r.data.next.patient_name });",
  "        toast('Called: ' + r.data.next.token_number,'success');",
  "        loadQueue(doctorId);",
  "      } else { toast('No more patients in queue','info'); }",
  "    } catch(e) { toast('Failed to call next','error'); }",
  "  };",
  "",
  "  const current = queue.find(q=>q.status==='in_progress');",
  "  const waiting = queue.filter(q=>q.status==='waiting');",
  "  const done = queue.filter(q=>q.status==='completed');",
  "",
  "  if (role === 'patient') return (",
  "    <div className='fu'>",
  "      {!myEntry ? (",
  "        <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:28}}>",
  "          <div style={{fontFamily:'Syne,sans-serif',fontSize:15,fontWeight:700,marginBottom:16}}>Join Queue</div>",
  "          {appts.length === 0 ? (",
  "            <div style={{textAlign:'center',padding:'32px 0',color:'var(--txt3)',fontSize:14}}>",
  "              <i className='fas fa-ticket-alt' style={{fontSize:36,display:'block',marginBottom:12}}/>",
  "              No confirmed appointments to join queue for.",
  "            </div>",
  "          ) : appts.map(a=>(",
  "            <div key={a.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'14px',background:'var(--surf2)',borderRadius:12,marginBottom:10}}>",
  "              <div>",
  "                <div style={{fontWeight:600,fontSize:14,marginBottom:3}}>{a.doctor_name||'Doctor'}</div>",
  "                <div style={{fontSize:12,color:'var(--txt3)'}}>{new Date(a.appointment_time).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</div>",
  "              </div>",
  "              <button onClick={()=>joinQueue(a.id, a.doctor_id)} disabled={joining} style={{padding:'8px 16px',background:tg,color:'#fff',border:'none',borderRadius:9,fontFamily:'DM Sans,sans-serif',fontSize:13,fontWeight:700,cursor:'pointer'}}>",
  "                {joining?'Joining...':'Join Queue'}",
  "              </button>",
  "            </div>",
  "          ))}",
  "        </div>",
  "      ) : (",
  "        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>",
  "          <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:28,textAlign:'center'}}>",
  "            <div style={{fontSize:11,fontWeight:700,textTransform:'uppercase',letterSpacing:.8,color:'var(--txt3)',marginBottom:4}}>Your Token</div>",
  "            <div style={{fontFamily:'Syne,sans-serif',fontSize:80,fontWeight:800,color:'var(--teal)',lineHeight:1,marginBottom:8}}>{myEntry.token_number?.split('-')[1]}</div>",
  "            <div style={{display:'inline-flex',alignItems:'center',gap:6,background:'var(--tealXL)',color:'var(--tealDk)',padding:'5px 14px',borderRadius:99,fontSize:12,fontWeight:700,marginBottom:20}}><i className='fas fa-ticket-alt'/>{myEntry.token_number}</div>",
  "            <div style={{width:'100%',height:7,background:'var(--surf2)',borderRadius:99,overflow:'hidden',marginBottom:14}}>",
  "              <div style={{height:'100%',background:tg,borderRadius:99,width: done.length+waiting.length>0 ? (done.length/(done.length+waiting.length+1)*100)+'%' : '0%',transition:'width 1s ease'}}/>",
  "            </div>",
  "            <div style={{fontFamily:'Syne,sans-serif',fontSize:32,fontWeight:800,color:'#F59E0B',marginBottom:4}}>~{myEntry.estimated_wait_minutes} min</div>",
  "            <div style={{color:'var(--txt3)',fontSize:13,marginBottom:20}}>Estimated wait time</div>",
  "            <div style={{display:'flex',gap:8,justifyContent:'center'}}>",
  "              <button onClick={()=>loadQueue(myEntry.doctor_id)} style={{padding:'9px 16px',background:tg,color:'#fff',border:'none',borderRadius:9,fontFamily:'DM Sans,sans-serif',fontSize:13,fontWeight:700,cursor:'pointer'}}><i className='fas fa-sync-alt' style={{marginRight:6}}/>Refresh</button>",
  "            </div>",
  "          </div>",
  "          <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:22}}>",
  "            <div style={{fontFamily:'Syne,sans-serif',fontSize:14,fontWeight:700,marginBottom:14}}>Live Queue</div>",
  "            {loading ? <div style={{color:'var(--txt3)',fontSize:13}}>Loading...</div> : queue.map((q,i)=>(",
  "              <div key={i} style={{display:'flex',alignItems:'center',gap:10,padding:'10px',borderRadius:10,marginBottom:6,background:q.token_number===myEntry.token_number?'var(--tealXL)':q.status==='in_progress'?'#DBEAFE':'var(--surf2)',border:q.token_number===myEntry.token_number?'1.5px solid var(--teal)':'1px solid transparent'}}>",
  "                <div style={{width:36,height:36,borderRadius:9,background:q.status==='in_progress'?tg:'var(--bdr)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,fontWeight:700,color:q.status==='in_progress'?'#fff':'var(--txt3)',flexShrink:0}}>{q.token_number?.split('-')[1]}</div>",
  "                <div style={{flex:1}}><div style={{fontSize:13,fontWeight:600}}>{q.patient_name}</div><div style={{fontSize:11,color:'var(--txt3)'}}>{q.token_number}</div></div>",
  "                <span style={{fontSize:10,padding:'2px 8px',borderRadius:99,fontWeight:700,background:q.status==='completed'?'#D1FAE5':q.status==='in_progress'?'#DBEAFE':'#FEF3C7',color:q.status==='completed'?'#065F46':q.status==='in_progress'?'#1E40AF':'#92400E'}}>{q.status}</span>",
  "              </div>",
  "            ))}",
  "          </div>",
  "        </div>",
  "      )}",
  "    </div>",
  "  );",
  "",
  "  return (",
  "    <div className='fu'>",
  "      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>",
  "        <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:28,textAlign:'center'}}>",
  "          <div style={{fontSize:11,fontWeight:700,textTransform:'uppercase',letterSpacing:.8,color:'var(--txt3)',marginBottom:4}}>Now Serving</div>",
  "          <div style={{fontFamily:'Syne,sans-serif',fontSize:72,fontWeight:800,color:'var(--teal)',lineHeight:1,marginBottom:8}}>{current?current.token_number?.split('-')[1]:'—'}</div>",
  "          <div style={{fontWeight:600,marginBottom:4}}>{current?.patient_name||'Queue Empty'}</div>",
  "          <div style={{color:'var(--txt3)',fontSize:12,marginBottom:22}}>Waiting: {waiting.length} · Done: {done.length}</div>",
  "          <div style={{display:'flex',gap:10,justifyContent:'center'}}>",
  "            <button onClick={callNext} style={{padding:'11px 22px',background:tg,color:'#fff',border:'none',borderRadius:10,fontFamily:'DM Sans,sans-serif',fontSize:14,fontWeight:700,cursor:'pointer',display:'flex',alignItems:'center',gap:7}}><i className='fas fa-arrow-right'/>Call Next</button>",
  "            <button onClick={()=>loadQueue(doctorId)} style={{padding:'11px 16px',background:'var(--surf2)',color:'var(--txt)',border:'1px solid var(--bdr)',borderRadius:10,fontFamily:'DM Sans,sans-serif',fontSize:13,fontWeight:600,cursor:'pointer'}}><i className='fas fa-sync-alt'/></button>",
  "          </div>",
  "        </div>",
  "        <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:22}}>",
  "          <div style={{fontFamily:'Syne,sans-serif',fontSize:14,fontWeight:700,marginBottom:14}}>Waiting List ({waiting.length})</div>",
  "          {waiting.length===0?<div style={{textAlign:'center',padding:'24px 0',color:'var(--txt3)',fontSize:13}}>No patients waiting</div>:waiting.map((q,i)=>(",
  "            <div key={i} style={{display:'flex',alignItems:'center',gap:10,padding:'11px',background:'var(--surf2)',borderRadius:10,marginBottom:8}}>",
  "              <div style={{width:34,height:34,borderRadius:9,background:'var(--bdr)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,fontWeight:700,color:'var(--txt3)',flexShrink:0}}>{q.token_number?.split('-')[1]}</div>",
  "              <div style={{flex:1}}><div style={{fontSize:13,fontWeight:600}}>{q.patient_name}</div><div style={{fontSize:11,color:'var(--txt3)'}}>~{q.estimated_wait_minutes} min wait</div></div>",
  "              <span style={{fontSize:10,padding:'2px 8px',borderRadius:99,fontWeight:700,background:'#FEF3C7',color:'#92400E'}}>#{q.position}</span>",
  "            </div>",
  "          ))}",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "}"
].join('\n'));

// ── src/pages/panels/AdminPanel.jsx
fs.writeFileSync('src/pages/panels/AdminPanel.jsx', [
  "import { useState, useEffect } from 'react';",
  "import { adminAPI } from '../../services/api';",
  "import { toast } from '../../components/ToastStack';",
  "const tg = 'linear-gradient(135deg,#0D9B82,#1DBEA0)';",
  "",
  "export default function AdminPanel() {",
  "  const [stats, setStats] = useState(null);",
  "  const [users, setUsers] = useState([]);",
  "  const [tab, setTab] = useState('stats');",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    Promise.all([adminAPI.getStats(), adminAPI.getUsers()])",
  "      .then(([s, u]) => { setStats(s.data.stats); setUsers(u.data.users||[]); })",
  "      .catch(() => toast('Failed to load admin data','error'))",
  "      .finally(() => setLoading(false));",
  "  }, []);",
  "",
  "  if (loading) return <div style={{padding:40,color:'var(--txt2)',fontSize:14}}>Loading admin data...</div>;",
  "",
  "  const mc = (label, val, icon, bg, color) => (",
  "    <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:14,padding:'18px 20px',position:'relative',overflow:'hidden'}}>",
  "      <div style={{fontSize:11,fontWeight:700,color:'var(--txt3)',textTransform:'uppercase',letterSpacing:.6,marginBottom:7}}>{label}</div>",
  "      <div style={{fontFamily:'Syne,sans-serif',fontSize:28,fontWeight:700}}>{val}</div>",
  "      <div style={{position:'absolute',top:14,right:14,width:38,height:38,borderRadius:10,background:bg,display:'flex',alignItems:'center',justifyContent:'center',fontSize:16,color}}><i className={'fas fa-'+icon}/></div>",
  "    </div>",
  "  );",
  "",
  "  return (",
  "    <div className='fu'>",
  "      {stats && (",
  "        <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14,marginBottom:20}}>",
  "          {mc('Total Patients', stats.totalPatients, 'users', '#E6F7F4', '#0D9B82')}",
  "          {mc('Active Doctors', stats.activeDoctors, 'user-md', '#EDE9FE', '#7C3AED')}",
  "          {mc(\"Today's Appts\", stats.todayAppointments, 'calendar-check', '#FEF3C7', '#F59E0B')}",
  "          {mc('Queue Size', stats.currentQueueSize, 'ticket-alt', '#FFE4E6', '#F43F5E')}",
  "        </div>",
  "      )}",
  "      <div style={{display:'flex',gap:4,background:'var(--surf2)',borderRadius:10,padding:4,marginBottom:18,width:'fit-content'}}>",
  "        {['stats','users'].map(t=>(",
  "          <button key={t} onClick={()=>setTab(t)} style={{padding:'8px 18px',border:'none',borderRadius:8,fontFamily:'DM Sans,sans-serif',fontSize:13,fontWeight:600,cursor:'pointer',background:tab===t?'var(--surf)':'transparent',color:tab===t?'var(--teal)':'var(--txt2)',transition:'all .2s',textTransform:'capitalize'}}>{t==='stats'?'System Stats':'All Users'}</button>",
  "        ))}",
  "      </div>",
  "      {tab==='stats' && (",
  "        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>",
  "          <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:22}}>",
  "            <div style={{fontFamily:'Syne,sans-serif',fontSize:14,fontWeight:700,marginBottom:16}}>System Status</div>",
  "            {[['API Server','Operational','#D1FAE5','#065F46'],['PostgreSQL DB','Connected','#D1FAE5','#065F46'],['WebSocket','Active','#D1FAE5','#065F46'],['Queue Engine','Running','#D1FAE5','#065F46']].map(([s,v,bg,c])=>(",
  "              <div key={s} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'11px 0',borderBottom:'1px solid var(--bdr)',fontSize:13}}>",
  "                <span>{s}</span>",
  "                <span style={{fontSize:11,padding:'3px 10px',borderRadius:99,fontWeight:700,background:bg,color:c}}>{v}</span>",
  "              </div>",
  "            ))}",
  "          </div>",
  "          <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:22}}>",
  "            <div style={{fontFamily:'Syne,sans-serif',fontSize:14,fontWeight:700,marginBottom:16}}>User Breakdown</div>",
  "            {[['Patients',users.filter(u=>u.role==='patient').length,'#E6F7F4','#0D9B82'],['Doctors',users.filter(u=>u.role==='doctor').length,'#EDE9FE','#7C3AED'],['Admins',users.filter(u=>u.role==='admin').length,'#FEF3C7','#F59E0B']].map(([l,v,bg,c])=>(",
  "              <div key={l} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'11px 0',borderBottom:'1px solid var(--bdr)',fontSize:13}}>",
  "                <span>{l}</span>",
  "                <span style={{fontSize:13,fontWeight:700,padding:'3px 12px',borderRadius:99,background:bg,color:c}}>{v}</span>",
  "              </div>",
  "            ))}",
  "          </div>",
  "        </div>",
  "      )}",
  "      {tab==='users' && (",
  "        <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,overflow:'hidden'}}>",
  "          <table style={{width:'100%',borderCollapse:'collapse'}}>",
  "            <thead><tr style={{borderBottom:'1px solid var(--bdr)'}}>",
  "              {['Name','Email','Phone','Role','Status','Joined'].map(h=>(",
  "                <th key={h} style={{fontSize:11,fontWeight:700,letterSpacing:.7,textTransform:'uppercase',color:'var(--txt3)',padding:'12px 14px',textAlign:'left'}}>{h}</th>",
  "              ))}",
  "            </tr></thead>",
  "            <tbody>",
  "              {users.map((u,i)=>(",
  "                <tr key={i} style={{borderBottom:'1px solid var(--bdr)'}} onMouseEnter={e=>e.currentTarget.style.background='var(--surf2)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>",
  "                  <td style={{padding:'12px 14px',fontSize:13,fontWeight:600}}>{u.name}</td>",
  "                  <td style={{padding:'12px 14px',fontSize:13,color:'var(--txt2)'}}>{u.email}</td>",
  "                  <td style={{padding:'12px 14px',fontSize:13,color:'var(--txt2)'}}>{u.phone||'—'}</td>",
  "                  <td style={{padding:'12px 14px'}}><span style={{fontSize:11,padding:'3px 9px',borderRadius:99,fontWeight:700,background:u.role==='admin'?'#FEF3C7':u.role==='doctor'?'#EDE9FE':'#E6F7F4',color:u.role==='admin'?'#92400E':u.role==='doctor'?'#5B21B6':'#065F46',textTransform:'capitalize'}}>{u.role}</span></td>",
  "                  <td style={{padding:'12px 14px'}}><span style={{fontSize:11,padding:'3px 9px',borderRadius:99,fontWeight:700,background:u.is_active?'#D1FAE5':'#FFE4E6',color:u.is_active?'#065F46':'#9F1239'}}>{u.is_active?'Active':'Inactive'}</span></td>",
  "                  <td style={{padding:'12px 14px',fontSize:12,color:'var(--txt3)'}}>{new Date(u.created_at).toLocaleDateString('en-IN')}</td>",
  "                </tr>",
  "              ))}",
  "            </tbody>",
  "          </table>",
  "        </div>",
  "      )}",
  "    </div>",
  "  );",
  "}"
].join('\n'));

// ── Update src/pages/Dashboard.jsx with all panels
fs.writeFileSync('src/pages/Dashboard.jsx', [
  "import { useState } from 'react';",
  "import { useAuth } from '../context/AuthContext';",
  "import { adminAPI, appointmentAPI, doctorAPI } from '../services/api';",
  "import { useEffect } from 'react';",
  "import AppointmentsPanel from './panels/AppointmentsPanel';",
  "import QueuePanel from './panels/QueuePanel';",
  "import AdminPanel from './panels/AdminPanel';",
  "import ToastStack from '../components/ToastStack';",
  "import Chatbot from '../components/Chatbot';",
  "const tg = 'linear-gradient(135deg,#0D9B82,#1DBEA0)';",
  "",
  "function Sidebar({ role, active, onNav, user, onLogout }) {",
  "  const navs = {",
  "    patient: [",
  "      { id:'overview', icon:'fa-home', label:'Dashboard' },",
  "      { id:'appointments', icon:'fa-calendar-check', label:'Appointments' },",
  "      { id:'queue', icon:'fa-ticket-alt', label:'Queue Status' },",
  "      { id:'doctors', icon:'fa-user-md', label:'Find Doctors' },",
  "      { id:'settings', icon:'fa-cog', label:'Settings' }",
  "    ],",
  "    doctor: [",
  "      { id:'overview', icon:'fa-home', label:'Dashboard' },",
  "      { id:'queue', icon:'fa-ticket-alt', label:'Queue Mgmt' },",
  "      { id:'appointments', icon:'fa-calendar-alt', label:'Schedule' },",
  "      { id:'settings', icon:'fa-cog', label:'Settings' }",
  "    ],",
  "    admin: [",
  "      { id:'overview', icon:'fa-home', label:'Overview' },",
  "      { id:'admin', icon:'fa-chart-bar', label:'Analytics' },",
  "      { id:'appointments', icon:'fa-calendar-alt', label:'Appointments' },",
  "      { id:'doctors', icon:'fa-user-md', label:'Doctors' },",
  "      { id:'settings', icon:'fa-cog', label:'Settings' }",
  "    ]",
  "  };",
  "  return (",
  "    <aside style={{width:250,background:'var(--surf)',borderRight:'1px solid var(--bdr)',height:'100vh',display:'flex',flexDirection:'column',flexShrink:0}}>",
  "      <div style={{padding:'18px 14px',borderBottom:'1px solid var(--bdr)',display:'flex',alignItems:'center',gap:9}}>",
  "        <div style={{width:32,height:32,background:tg,borderRadius:9,display:'flex',alignItems:'center',justifyContent:'center'}}><i className='fas fa-heart-pulse' style={{color:'#fff',fontSize:14}}/></div>",
  "        <span style={{fontFamily:'Syne,sans-serif',fontWeight:700,fontSize:16,background:tg,WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'}}>MEDIQUEUE</span>",
  "      </div>",
  "      <div style={{flex:1,padding:'10px 8px',overflowY:'auto'}}>",
  "        {(navs[role]||navs.patient).map(item=>(",
  "          <div key={item.id} onClick={()=>onNav(item.id)} style={{display:'flex',alignItems:'center',gap:9,padding:'9px 11px',borderRadius:10,cursor:'pointer',marginBottom:2,background:active===item.id?'var(--tealXL)':'transparent',color:active===item.id?'var(--teal)':'var(--txt2)',fontWeight:active===item.id?600:500,fontSize:13,transition:'all .2s'}}>",
  "            <div style={{width:30,height:30,borderRadius:8,background:active===item.id?tg:'transparent',display:'flex',alignItems:'center',justifyContent:'center',fontSize:13,color:active===item.id?'#fff':'inherit'}}><i className={'fas '+item.icon}/></div>",
  "            {item.label}",
  "          </div>",
  "        ))}",
  "      </div>",
  "      <div style={{padding:'10px 8px',borderTop:'1px solid var(--bdr)'}}>",
  "        <div onClick={onLogout} style={{display:'flex',alignItems:'center',gap:9,padding:'9px 11px',borderRadius:10,cursor:'pointer',color:'var(--txt2)',fontSize:13,transition:'all .2s'}} onMouseEnter={e=>e.currentTarget.style.background='var(--surf2)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>",
  "          <div style={{width:32,height:32,borderRadius:9,background:tg,display:'flex',alignItems:'center',justifyContent:'center',color:'#fff',fontWeight:700,fontSize:13,flexShrink:0}}>{user?.name?.slice(0,2).toUpperCase()}</div>",
  "          <div style={{flex:1}}><div style={{fontSize:12,fontWeight:600}}>{user?.name}</div><div style={{fontSize:10,color:'var(--txt3)',textTransform:'capitalize'}}>{user?.role}</div></div>",
  "          <i className='fas fa-sign-out-alt' style={{fontSize:13}}/>",
  "        </div>",
  "      </div>",
  "    </aside>",
  "  );",
  "}",
  "",
  "function MetricCard({ label, val, icon, color='#0D9B82', bg='#E6F7F4' }) {",
  "  return (",
  "    <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:'18px 20px',position:'relative',overflow:'hidden'}}>",
  "      <div style={{fontSize:11,fontWeight:700,color:'var(--txt3)',textTransform:'uppercase',letterSpacing:.6,marginBottom:7}}>{label}</div>",
  "      <div style={{fontFamily:'Syne,sans-serif',fontSize:28,fontWeight:700}}>{val}</div>",
  "      <div style={{position:'absolute',top:14,right:14,width:38,height:38,borderRadius:10,background:bg,display:'flex',alignItems:'center',justifyContent:'center',fontSize:16,color}}><i className={'fas fa-'+icon}/></div>",
  "    </div>",
  "  );",
  "}",
  "",
  "function OverviewPanel({ role }) {",
  "  const [stats, setStats] = useState(null);",
  "  const [appointments, setAppointments] = useState([]);",
  "  const [loading, setLoading] = useState(true);",
  "  useEffect(() => {",
  "    const load = async () => {",
  "      try {",
  "        if (role==='admin') { const r=await adminAPI.getStats(); setStats(r.data.stats); }",
  "        const r2=await appointmentAPI.getAll(); setAppointments(r2.data.appointments||[]);",
  "      } catch(e){console.error(e);} finally{setLoading(false);}",
  "    };",
  "    load();",
  "  }, [role]);",
  "  if (loading) return <div style={{padding:40,color:'var(--txt2)',fontSize:14}}>Loading...</div>;",
  "  return (",
  "    <div className='fu'>",
  "      <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14,marginBottom:20}}>",
  "        {role==='admin'&&stats&&<>",
  "          <MetricCard label='Total Patients' val={stats.totalPatients} icon='users' color='#0D9B82' bg='#E6F7F4'/>",
  "          <MetricCard label='Active Doctors' val={stats.activeDoctors} icon='user-md' color='#7C3AED' bg='#EDE9FE'/>",
  "          <MetricCard label=\"Today's Appts\" val={stats.todayAppointments} icon='calendar-check' color='#F59E0B' bg='#FEF3C7'/>",
  "          <MetricCard label='Queue Size' val={stats.currentQueueSize} icon='ticket-alt' color='#F43F5E' bg='#FFE4E6'/>",
  "        </>}",
  "        {role==='patient'&&<>",
  "          <MetricCard label='Total Appointments' val={appointments.length} icon='calendar-check' color='#0D9B82' bg='#E6F7F4'/>",
  "          <MetricCard label='Upcoming' val={appointments.filter(a=>a.status==='confirmed').length} icon='clock' color='#7C3AED' bg='#EDE9FE'/>",
  "          <MetricCard label='Completed' val={appointments.filter(a=>a.status==='completed').length} icon='check-circle' color='#10B981' bg='#D1FAE5'/>",
  "          <MetricCard label='Cancelled' val={appointments.filter(a=>a.status==='cancelled').length} icon='times-circle' color='#F43F5E' bg='#FFE4E6'/>",
  "        </>}",
  "        {role==='doctor'&&<>",
  "          <MetricCard label=\"Today's Patients\" val={appointments.length} icon='users' color='#0D9B82' bg='#E6F7F4'/>",
  "          <MetricCard label='Confirmed' val={appointments.filter(a=>a.status==='confirmed').length} icon='calendar-check' color='#7C3AED' bg='#EDE9FE'/>",
  "          <MetricCard label='Completed' val={appointments.filter(a=>a.status==='completed').length} icon='check-circle' color='#10B981' bg='#D1FAE5'/>",
  "          <MetricCard label='Pending' val={appointments.filter(a=>a.status==='pending').length} icon='clock' color='#F59E0B' bg='#FEF3C7'/>",
  "        </>}",
  "      </div>",
  "      <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:22}}>",
  "        <div style={{fontFamily:'Syne,sans-serif',fontSize:15,fontWeight:700,marginBottom:16}}>Recent Appointments</div>",
  "        {appointments.length===0?(",
  "          <div style={{textAlign:'center',padding:'32px 0',color:'var(--txt3)',fontSize:14}}><i className='fas fa-calendar' style={{fontSize:36,display:'block',marginBottom:12}}/>No appointments yet</div>",
  "        ):(",
  "          <table style={{width:'100%',borderCollapse:'collapse'}}>",
  "            <thead><tr>{['Date & Time',role==='doctor'?'Patient':'Doctor','Type','Status'].map(h=>(",
  "              <th key={h} style={{fontSize:11,fontWeight:700,letterSpacing:.7,textTransform:'uppercase',color:'var(--txt3)',padding:'9px 12px',borderBottom:'1px solid var(--bdr)',textAlign:'left'}}>{h}</th>",
  "            ))}</tr></thead>",
  "            <tbody>{appointments.slice(0,6).map((a,i)=>(",
  "              <tr key={i} style={{borderBottom:'1px solid var(--bdr)'}} onMouseEnter={e=>e.currentTarget.style.background='var(--surf2)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>",
  "                <td style={{padding:'12px',fontSize:13,fontWeight:600}}>{new Date(a.appointment_time).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</td>",
  "                <td style={{padding:'12px',fontSize:13}}>{role==='doctor'?a.patient_name:a.doctor_name||'—'}</td>",
  "                <td style={{padding:'12px'}}><span style={{fontSize:11,padding:'3px 9px',borderRadius:99,fontWeight:700,background:a.type==='telehealth'?'#EDE9FE':'#DBEAFE',color:a.type==='telehealth'?'#5B21B6':'#1E40AF'}}>{a.type}</span></td>",
  "                <td style={{padding:'12px'}}><span style={{fontSize:11,padding:'3px 9px',borderRadius:99,fontWeight:700,background:a.status==='confirmed'?'#D1FAE5':a.status==='completed'?'#E6F7F4':'#FFE4E6',color:a.status==='confirmed'?'#065F46':a.status==='completed'?'#0A7A67':'#9F1239'}}>{a.status}</span></td>",
  "              </tr>",
  "            ))}</tbody>",
  "          </table>",
  "        )}",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  "",
  "function DoctorsPanel() {",
  "  const [doctors, setDoctors] = useState([]);",
  "  const [loading, setLoading] = useState(true);",
  "  useEffect(()=>{ doctorAPI.getAll().then(r=>setDoctors(r.data.doctors||[])).catch(console.error).finally(()=>setLoading(false)); },[]);",
  "  if (loading) return <div style={{padding:40,color:'var(--txt2)',fontSize:14}}>Loading doctors...</div>;",
  "  return (",
  "    <div className='fu' style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(210px,1fr))',gap:16}}>",
  "      {doctors.length===0?(",
  "        <div style={{gridColumn:'1/-1',textAlign:'center',padding:48,color:'var(--txt3)'}}><i className='fas fa-user-md' style={{fontSize:40,display:'block',marginBottom:12}}/>No doctors found</div>",
  "      ):doctors.map(d=>(",
  "        <div key={d.id} style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:22,textAlign:'center',transition:'all .2s'}} onMouseEnter={e=>e.currentTarget.style.boxShadow='0 8px 24px rgba(0,0,0,.1)'} onMouseLeave={e=>e.currentTarget.style.boxShadow='none'}>",
  "          <div style={{width:64,height:64,borderRadius:16,background:tg,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:700,fontSize:22,color:'#fff',margin:'0 auto 12px'}}>{d.name?.slice(0,2).toUpperCase()}</div>",
  "          <div style={{fontWeight:700,fontSize:14,marginBottom:3}}>{d.name}</div>",
  "          <div style={{color:'var(--txt3)',fontSize:12,marginBottom:8}}>{d.speciality}</div>",
  "          <div style={{color:'#F59E0B',fontSize:12,marginBottom:10}}>★ {d.rating} · {d.experience_years} yrs</div>",
  "          <div style={{fontFamily:'Syne,sans-serif',fontSize:15,fontWeight:700,color:'var(--teal)',marginBottom:14}}>₹{d.consultation_fee}</div>",
  "          <div style={{display:'flex',gap:6}}>",
  "            <button style={{flex:1,padding:'8px',background:tg,color:'#fff',border:'none',borderRadius:8,fontFamily:'DM Sans,sans-serif',fontSize:12,fontWeight:700,cursor:'pointer'}}>Book</button>",
  "            <button style={{padding:'8px 10px',background:'var(--surf2)',color:'var(--txt2)',border:'1px solid var(--bdr)',borderRadius:8,fontFamily:'DM Sans,sans-serif',fontSize:12,cursor:'pointer'}}>View</button>",
  "          </div>",
  "        </div>",
  "      ))}",
  "    </div>",
  "  );",
  "}",
  "",
  "function SettingsPanel({ user }) {",
  "  return (",
  "    <div className='fu' style={{maxWidth:500}}>",
  "      <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:28}}>",
  "        <div style={{fontFamily:'Syne,sans-serif',fontSize:15,fontWeight:700,marginBottom:20}}>Account Details</div>",
  "        {[['Full Name',user?.name],['Email',user?.email],['Role',user?.role]].map(([l,v])=>(",
  "          <div key={l} style={{marginBottom:16}}>",
  "            <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:5,textTransform:'uppercase',letterSpacing:.4}}>{l}</label>",
  "            <input defaultValue={v} readOnly style={{width:'100%',padding:'11px 14px',background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:10,fontSize:13,color:'var(--txt)',outline:'none'}}/>",
  "          </div>",
  "        ))}",
  "        <div style={{padding:'12px 14px',background:'var(--tealXL)',borderRadius:10,fontSize:13,color:'var(--tealDk)',display:'flex',alignItems:'center',gap:8}}>",
  "          <i className='fas fa-database'/> Connected to live PostgreSQL database",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  "",
  "export default function Dashboard() {",
  "  const { user, logout } = useAuth();",
  "  const [panel, setPanel] = useState('overview');",
  "  const titles = { overview:'Dashboard', appointments:'Appointments', queue:user?.role==='doctor'?'Queue Management':'Queue Status', doctors:'Find Doctors', admin:'Analytics', settings:'Settings' };",
  "",
  "  const renderPanel = () => {",
  "    switch(panel) {",
  "      case 'overview': return <OverviewPanel role={user?.role}/>;",
  "      case 'appointments': return <AppointmentsPanel role={user?.role}/>;",
  "      case 'queue': return <QueuePanel role={user?.role}/>;",
  "      case 'doctors': return <DoctorsPanel/>;",
  "      case 'admin': return <AdminPanel/>;",
  "      case 'settings': return <SettingsPanel user={user}/>;",
  "      default: return <div style={{padding:40,color:'var(--txt2)'}}>Coming soon...</div>;",
  "    }",
  "  };",
  "",
  "  return (",
  "    <div style={{display:'flex',height:'100vh',overflow:'hidden'}}>",
  "      <ToastStack/>",
  "      <Sidebar role={user?.role} active={panel} onNav={setPanel} user={user} onLogout={logout}/>",
  "      <div style={{flex:1,display:'flex',flexDirection:'column',overflow:'hidden'}}>",
  "        <div style={{height:62,padding:'0 24px',display:'flex',alignItems:'center',justifyContent:'space-between',background:'var(--surf)',borderBottom:'1px solid var(--bdr)',flexShrink:0}}>",
  "          <div>",
  "            <div style={{fontFamily:'Syne,sans-serif',fontSize:18,fontWeight:700}}>{titles[panel]||panel}</div>",
  "            <div style={{fontSize:11,color:'var(--txt3)'}}>Welcome back, {user?.name}!</div>",
  "          </div>",
  "          <div style={{display:'flex',alignItems:'center',gap:10}}>",
  "            <span style={{fontSize:12,padding:'4px 12px',borderRadius:99,fontWeight:700,background:'#E6F7F4',color:'#0A7A67',textTransform:'capitalize'}}>{user?.role}</span>",
  "            <div style={{width:36,height:36,borderRadius:9,background:tg,display:'flex',alignItems:'center',justifyContent:'center',color:'#fff',fontWeight:700,fontSize:13}}>{user?.name?.slice(0,2).toUpperCase()}</div>",
  "          </div>",
  "        </div>",
  "        <div style={{flex:1,overflowY:'auto',padding:24}} key={panel}>",
  "          {renderPanel()}",
  "        </div>",
  "      </div>",
  "      <Chatbot/>",
  "    </div>",
  "  );",
  "}"
].join('\n'));

console.log('');
console.log('✅ PHASE 4 COMPLETE — ALL FILES WRITTEN!');
console.log('');