const fs = require('fs');

// ── src/services/api.js
fs.writeFileSync('src/services/api.js', [
  "import axios from 'axios';",
  "",
  "const api = axios.create({",
  "  baseURL: import.meta.env.VITE_API_URL || 'http://localhost:5000/api',",
  "  withCredentials: true",
  "});",
  "",
  "api.interceptors.request.use(config => {",
  "  const token = localStorage.getItem('mq_token');",
  "  if (token) config.headers.Authorization = 'Bearer ' + token;",
  "  return config;",
  "});",
  "",
  "api.interceptors.response.use(",
  "  res => res,",
  "  err => {",
  "    if (err.response?.status === 401) {",
  "      localStorage.removeItem('mq_token');",
  "      localStorage.removeItem('mq_user');",
  "      window.location.href = '/';",
  "    }",
  "    return Promise.reject(err);",
  "  }",
  ");",
  "",
  "export const authAPI = {",
  "  login: (data) => api.post('/auth/login', data),",
  "  register: (data) => api.post('/auth/register', data),",
  "  me: () => api.get('/auth/me')",
  "};",
  "",
  "export const appointmentAPI = {",
  "  getAll: () => api.get('/appointments'),",
  "  book: (data) => api.post('/appointments', data),",
  "  cancel: (id) => api.patch('/appointments/' + id + '/cancel')",
  "};",
  "",
  "export const queueAPI = {",
  "  join: (appointment_id) => api.post('/queue/join', { appointment_id }),",
  "  getStatus: (doctorId) => api.get('/queue/' + doctorId + '/status'),",
  "  callNext: (doctorId) => api.post('/queue/' + doctorId + '/next')",
  "};",
  "",
  "export const doctorAPI = {",
  "  getAll: () => api.get('/doctors'),",
  "  getById: (id) => api.get('/doctors/' + id),",
  "  getAvailability: (id, date) => api.get('/doctors/' + id + '/availability?date=' + date)",
  "};",
  "",
  "export const adminAPI = {",
  "  getStats: () => api.get('/admin/stats'),",
  "  getUsers: () => api.get('/admin/users')",
  "};",
  "",
  "export default api;"
].join('\n'));

// ── src/services/socket.js
fs.writeFileSync('src/services/socket.js', [
  "import { io } from 'socket.io-client';",
  "",
  "const socket = io(import.meta.env.VITE_SOCKET_URL || 'http://localhost:5000', {",
  "  autoConnect: false,",
  "  transports: ['websocket']",
  "});",
  "",
  "export const connectSocket = () => socket.connect();",
  "export const disconnectSocket = () => socket.disconnect();",
  "export const joinQueueRoom = (doctorId) => socket.emit('join_queue_room', doctorId);",
  "export const onQueueUpdated = (cb) => socket.on('queue_updated', cb);",
  "export const offQueueUpdated = () => socket.off('queue_updated');",
  "export const emitCallNext = (data) => socket.emit('call_next_patient', data);",
  "",
  "export default socket;"
].join('\n'));

// ── src/context/AuthContext.jsx
fs.writeFileSync('src/context/AuthContext.jsx', [
  "import { createContext, useContext, useState, useEffect } from 'react';",
  "import { authAPI } from '../services/api';",
  "import { connectSocket, disconnectSocket } from '../services/socket';",
  "",
  "const AuthContext = createContext(null);",
  "",
  "export function AuthProvider({ children }) {",
  "  const [user, setUser] = useState(null);",
  "  const [token, setToken] = useState(localStorage.getItem('mq_token'));",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    const init = async () => {",
  "      const t = localStorage.getItem('mq_token');",
  "      const u = localStorage.getItem('mq_user');",
  "      if (t && u) {",
  "        setToken(t);",
  "        setUser(JSON.parse(u));",
  "        connectSocket();",
  "      }",
  "      setLoading(false);",
  "    };",
  "    init();",
  "  }, []);",
  "",
  "  const login = async (email, password) => {",
  "    const res = await authAPI.login({ email, password });",
  "    const { token, user } = res.data;",
  "    localStorage.setItem('mq_token', token);",
  "    localStorage.setItem('mq_user', JSON.stringify(user));",
  "    setToken(token);",
  "    setUser(user);",
  "    connectSocket();",
  "    return user;",
  "  };",
  "",
  "  const register = async (data) => {",
  "    const res = await authAPI.register(data);",
  "    const { token, user } = res.data;",
  "    localStorage.setItem('mq_token', token);",
  "    localStorage.setItem('mq_user', JSON.stringify(user));",
  "    setToken(token);",
  "    setUser(user);",
  "    connectSocket();",
  "    return user;",
  "  };",
  "",
  "  const logout = () => {",
  "    localStorage.removeItem('mq_token');",
  "    localStorage.removeItem('mq_user');",
  "    setToken(null);",
  "    setUser(null);",
  "    disconnectSocket();",
  "  };",
  "",
  "  return (",
  "    <AuthContext.Provider value={{ user, token, loading, login, register, logout }}>",
  "      {children}",
  "    </AuthContext.Provider>",
  "  );",
  "}",
  "",
  "export const useAuth = () => useContext(AuthContext);",
  "export default AuthContext;"
].join('\n'));

// ── src/main.jsx
fs.writeFileSync('src/main.jsx', [
  "import { StrictMode } from 'react';",
  "import { createRoot } from 'react-dom/client';",
  "import { BrowserRouter } from 'react-router-dom';",
  "import { AuthProvider } from './context/AuthContext';",
  "import App from './App';",
  "import './index.css';",
  "",
  "createRoot(document.getElementById('root')).render(",
  "  <StrictMode>",
  "    <BrowserRouter>",
  "      <AuthProvider>",
  "        <App />",
  "      </AuthProvider>",
  "    </BrowserRouter>",
  "  </StrictMode>",
  ");"
].join('\n'));

// ── src/index.css
fs.writeFileSync('src/index.css', [
  "@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;500;600;700;800&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600&display=swap');",
  "@import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css');",
  "*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}",
  ":root{",
  "  --teal:#0D9B82;--tealL:#1DBEA0;--tealXL:#E6F7F4;--tealDk:#0A7A67;",
  "  --emerald:#10B981;--gold:#F59E0B;--rose:#F43F5E;--violet:#7C3AED;--sky:#0EA5E9;",
  "  --ink:#0A1628;--slate:#64748B;--mist:#94A3B8;--snow:#F8FAFC;",
  "  --bg:#F8FAFC;--surf:#FFFFFF;--surf2:#F1F5F9;",
  "  --txt:#0A1628;--txt2:#64748B;--txt3:#94A3B8;",
  "  --bdr:#E2E8F0;--bdr2:#CBD5E1;",
  "  --fd:'Syne',sans-serif;--fb:'DM Sans',sans-serif;",
  "  --tg:linear-gradient(135deg,#0D9B82,#1DBEA0);",
  "}",
  "html,body,#root{height:100%;font-family:'DM Sans',sans-serif;background:var(--bg);color:var(--txt)}",
  "::-webkit-scrollbar{width:5px}",
  "::-webkit-scrollbar-thumb{background:var(--teal);border-radius:99px}",
  "a{text-decoration:none;color:inherit}",
  "button{font-family:'DM Sans',sans-serif}",
  "input,select,textarea{font-family:'DM Sans',sans-serif}",
  "@keyframes fadeUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}",
  "@keyframes scaleIn{from{opacity:0;transform:scale(.95)}to{opacity:1;transform:scale(1)}}",
  "@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}",
  "@keyframes spin{to{transform:rotate(360deg)}}",
  "@keyframes slideLeft{from{opacity:0;transform:translateX(16px)}to{opacity:1;transform:translateX(0)}}",
  ".fu{animation:fadeUp .5s ease both}",
  ".si{animation:scaleIn .3s ease both}",
  ".spin{animation:spin 1s linear infinite}"
].join('\n'));

// ── src/App.jsx
fs.writeFileSync('src/App.jsx', [
  "import { Routes, Route, Navigate } from 'react-router-dom';",
  "import { useAuth } from './context/AuthContext';",
  "import Landing from './pages/Landing';",
  "import Login from './pages/Login';",
  "import Register from './pages/Register';",
  "import Dashboard from './pages/Dashboard';",
  "",
  "function PrivateRoute({ children }) {",
  "  const { user, loading } = useAuth();",
  "  if (loading) return <div style={{display:'flex',alignItems:'center',justifyContent:'center',height:'100vh',fontSize:14,color:'var(--txt2)'}}>Loading...</div>;",
  "  return user ? children : <Navigate to='/login' replace />;",
  "}",
  "",
  "function PublicRoute({ children }) {",
  "  const { user, loading } = useAuth();",
  "  if (loading) return null;",
  "  return !user ? children : <Navigate to='/dashboard' replace />;",
  "}",
  "",
  "export default function App() {",
  "  return (",
  "    <Routes>",
  "      <Route path='/' element={<PublicRoute><Landing /></PublicRoute>} />",
  "      <Route path='/login' element={<PublicRoute><Login /></PublicRoute>} />",
  "      <Route path='/register' element={<PublicRoute><Register /></PublicRoute>} />",
  "      <Route path='/dashboard' element={<PrivateRoute><Dashboard /></PrivateRoute>} />",
  "      <Route path='/dashboard/*' element={<PrivateRoute><Dashboard /></PrivateRoute>} />",
  "      <Route path='*' element={<Navigate to='/' replace />} />",
  "    </Routes>",
  "  );",
  "}"
].join('\n'));

// ── src/pages/Login.jsx
fs.writeFileSync('src/pages/Login.jsx', [
  "import { useState } from 'react';",
  "import { useNavigate, Link } from 'react-router-dom';",
  "import { useAuth } from '../context/AuthContext';",
  "",
  "export default function Login() {",
  "  const { login } = useAuth();",
  "  const nav = useNavigate();",
  "  const [form, setForm] = useState({ email: '', password: '' });",
  "  const [error, setError] = useState('');",
  "  const [loading, setLoading] = useState(false);",
  "  const [role, setRole] = useState('patient');",
  "",
  "  const demos = {",
  "    patient: { email: 'patient@mediqueue.com', password: 'password' },",
  "    doctor:  { email: 'doctor@mediqueue.com',  password: 'password' },",
  "    admin:   { email: 'admin@mediqueue.com',   password: 'admin123' }",
  "  };",
  "",
  "  const fillDemo = (r) => { setRole(r); setForm(demos[r]); setError(''); };",
  "",
  "  const submit = async (e) => {",
  "    e.preventDefault();",
  "    setLoading(true); setError('');",
  "    try {",
  "      await login(form.email, form.password);",
  "      nav('/dashboard');",
  "    } catch (err) {",
  "      setError(err.response?.data?.message || 'Login failed. Check your credentials.');",
  "    } finally { setLoading(false); }",
  "  };",
  "",
  "  const tg = 'linear-gradient(135deg,#0D9B82,#1DBEA0)';",
  "",
  "  return (",
  "    <div style={{minHeight:'100vh',background:'var(--bg)',display:'flex',alignItems:'center',justifyContent:'center',padding:20}}>",
  "      <div className='si' style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:24,padding:40,width:'100%',maxWidth:420,boxShadow:'0 24px 64px rgba(0,0,0,.12)'}}>",
  "        <div style={{display:'flex',alignItems:'center',gap:10,marginBottom:24}}>",
  "          <div style={{width:40,height:40,background:tg,borderRadius:10,display:'flex',alignItems:'center',justifyContent:'center'}}><i className='fas fa-heart-pulse' style={{color:'#fff',fontSize:18}}/></div>",
  "          <div><div style={{fontFamily:'Syne,sans-serif',fontWeight:700,fontSize:19}}>MEDIQUEUE</div><div style={{fontSize:12,color:'var(--txt3)'}}>Sign in to your account</div></div>",
  "        </div>",
  "",
  "        <div style={{background:'var(--tealXL)',border:'1px solid rgba(13,155,130,.2)',borderRadius:10,padding:'10px 13px',fontSize:12,color:'var(--tealDk)',marginBottom:18}}>",
  "          <strong>Demo accounts:</strong> Click a role below to auto-fill",
  "        </div>",
  "",
  "        <div style={{display:'flex',gap:4,background:'var(--surf2)',borderRadius:10,padding:4,marginBottom:22}}>",
  "          {['patient','doctor','admin'].map(r => (",
  "            <button key={r} onClick={() => fillDemo(r)} style={{flex:1,padding:'8px 4px',border:'none',borderRadius:8,fontFamily:'DM Sans,sans-serif',fontSize:12,fontWeight:600,cursor:'pointer',background:role===r?'var(--surf)':'transparent',color:role===r?'var(--teal)':'var(--txt2)',transition:'all .2s',boxShadow:role===r?'0 1px 4px rgba(0,0,0,.08)':'none'}}>",
  "              {r==='patient'?'👤 Patient':r==='doctor'?'👨‍⚕️ Doctor':'👑 Admin'}",
  "            </button>",
  "          ))}",
  "        </div>",
  "",
  "        <form onSubmit={submit}>",
  "          <div style={{marginBottom:14}}>",
  "            <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:5,textTransform:'uppercase',letterSpacing:.4}}>Email</label>",
  "            <input type='email' value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))} placeholder='email@example.com' required style={{width:'100%',padding:'11px 14px',background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:10,fontSize:13,color:'var(--txt)',outline:'none'}}/>",
  "          </div>",
  "          <div style={{marginBottom:20}}>",
  "            <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:5,textTransform:'uppercase',letterSpacing:.4}}>Password</label>",
  "            <input type='password' value={form.password} onChange={e=>setForm(f=>({...f,password:e.target.value}))} placeholder='••••••••' required style={{width:'100%',padding:'11px 14px',background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:10,fontSize:13,color:'var(--txt)',outline:'none'}}/>",
  "          </div>",
  "          {error && <div style={{background:'#FFE4E6',color:'#9F1239',borderRadius:8,padding:'10px 13px',fontSize:13,marginBottom:14}}>{error}</div>}",
  "          <button type='submit' disabled={loading} style={{width:'100%',padding:'13px',background:tg,color:'#fff',border:'none',borderRadius:10,fontFamily:'DM Sans,sans-serif',fontSize:14,fontWeight:700,cursor:'pointer',boxShadow:'0 4px 14px rgba(13,155,130,.35)'}}>",
  "            {loading ? 'Signing in...' : 'Sign In'}",
  "          </button>",
  "        </form>",
  "        <div style={{textAlign:'center',marginTop:18,fontSize:13,color:'var(--txt2)'}}>",
  "          Don't have an account? <Link to='/register' style={{color:'var(--teal)',fontWeight:600}}>Register</Link>",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "}"
].join('\n'));

// ── src/pages/Register.jsx
fs.writeFileSync('src/pages/Register.jsx', [
  "import { useState } from 'react';",
  "import { useNavigate, Link } from 'react-router-dom';",
  "import { useAuth } from '../context/AuthContext';",
  "",
  "export default function Register() {",
  "  const { register } = useAuth();",
  "  const nav = useNavigate();",
  "  const [form, setForm] = useState({ name:'', email:'', phone:'', password:'', role:'patient' });",
  "  const [error, setError] = useState('');",
  "  const [loading, setLoading] = useState(false);",
  "  const tg = 'linear-gradient(135deg,#0D9B82,#1DBEA0)';",
  "",
  "  const submit = async (e) => {",
  "    e.preventDefault();",
  "    setLoading(true); setError('');",
  "    try {",
  "      await register(form);",
  "      nav('/dashboard');",
  "    } catch (err) {",
  "      setError(err.response?.data?.message || 'Registration failed.');",
  "    } finally { setLoading(false); }",
  "  };",
  "",
  "  const field = (label, key, type='text', ph='') => (",
  "    <div style={{marginBottom:14}}>",
  "      <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:5,textTransform:'uppercase',letterSpacing:.4}}>{label}</label>",
  "      <input type={type} value={form[key]} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))} placeholder={ph} required={key!=='phone'} style={{width:'100%',padding:'11px 14px',background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:10,fontSize:13,color:'var(--txt)',outline:'none'}}/>",
  "    </div>",
  "  );",
  "",
  "  return (",
  "    <div style={{minHeight:'100vh',background:'var(--bg)',display:'flex',alignItems:'center',justifyContent:'center',padding:20}}>",
  "      <div className='si' style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:24,padding:40,width:'100%',maxWidth:420,boxShadow:'0 24px 64px rgba(0,0,0,.12)'}}>",
  "        <div style={{fontFamily:'Syne,sans-serif',fontWeight:700,fontSize:22,marginBottom:6}}>Create Account</div>",
  "        <div style={{fontSize:13,color:'var(--txt2)',marginBottom:24}}>Join MEDIQUEUE today</div>",
  "        <form onSubmit={submit}>",
  "          {field('Full Name','name','text','Your full name')}",
  "          {field('Email','email','email','email@example.com')}",
  "          {field('Phone','phone','tel','+91 9876543210')}",
  "          {field('Password','password','password','Min 6 characters')}",
  "          <div style={{marginBottom:20}}>",
  "            <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:5,textTransform:'uppercase',letterSpacing:.4}}>Role</label>",
  "            <select value={form.role} onChange={e=>setForm(f=>({...f,role:e.target.value}))} style={{width:'100%',padding:'11px 14px',background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:10,fontSize:13,color:'var(--txt)',outline:'none'}}>",
  "              <option value='patient'>Patient</option>",
  "              <option value='doctor'>Doctor</option>",
  "            </select>",
  "          </div>",
  "          {error && <div style={{background:'#FFE4E6',color:'#9F1239',borderRadius:8,padding:'10px 13px',fontSize:13,marginBottom:14}}>{error}</div>}",
  "          <button type='submit' disabled={loading} style={{width:'100%',padding:'13px',background:tg,color:'#fff',border:'none',borderRadius:10,fontFamily:'DM Sans,sans-serif',fontSize:14,fontWeight:700,cursor:'pointer',boxShadow:'0 4px 14px rgba(13,155,130,.35)'}}>",
  "            {loading ? 'Creating account...' : 'Create Account'}",
  "          </button>",
  "        </form>",
  "        <div style={{textAlign:'center',marginTop:18,fontSize:13,color:'var(--txt2)'}}>",
  "          Already have an account? <Link to='/login' style={{color:'var(--teal)',fontWeight:600}}>Sign In</Link>",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "}"
].join('\n'));

// ── src/pages/Landing.jsx
fs.writeFileSync('src/pages/Landing.jsx', [
  "import { useNavigate } from 'react-router-dom';",
  "",
  "export default function Landing() {",
  "  const nav = useNavigate();",
  "  const tg = 'linear-gradient(135deg,#0D9B82,#1DBEA0)';",
  "",
  "  return (",
  "    <div style={{minHeight:'100vh',background:'var(--bg)'}}>",
  "      <nav style={{padding:'0 40px',height:66,display:'flex',alignItems:'center',justifyContent:'space-between',background:'var(--surf)',borderBottom:'1px solid var(--bdr)'}}>",
  "        <div style={{display:'flex',alignItems:'center',gap:10}}>",
  "          <div style={{width:36,height:36,background:tg,borderRadius:10,display:'flex',alignItems:'center',justifyContent:'center'}}><i className='fas fa-heart-pulse' style={{color:'#fff',fontSize:16}}/></div>",
  "          <span style={{fontFamily:'Syne,sans-serif',fontSize:19,fontWeight:700,background:tg,WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'}}>MEDIQUEUE</span>",
  "        </div>",
  "        <div style={{display:'flex',gap:10}}>",
  "          <button onClick={()=>nav('/login')} style={{padding:'8px 18px',background:'transparent',border:'1.5px solid var(--bdr2)',borderRadius:9,fontFamily:'DM Sans,sans-serif',fontSize:13,fontWeight:600,cursor:'pointer',color:'var(--txt)'}}>Log In</button>",
  "          <button onClick={()=>nav('/register')} style={{padding:'8px 18px',background:tg,border:'none',borderRadius:9,fontFamily:'DM Sans,sans-serif',fontSize:13,fontWeight:600,cursor:'pointer',color:'#fff',boxShadow:'0 4px 14px rgba(13,155,130,.3)'}}>Get Started Free</button>",
  "        </div>",
  "      </nav>",
  "      <div style={{maxWidth:1100,margin:'0 auto',padding:'100px 40px 60px',textAlign:'center'}}>",
  "        <div className='fu' style={{display:'inline-flex',alignItems:'center',gap:7,background:'var(--tealXL)',color:'var(--tealDk)',padding:'5px 14px',borderRadius:999,fontSize:11,fontWeight:700,letterSpacing:.8,textTransform:'uppercase',marginBottom:22}}>",
  "          <span style={{width:6,height:6,background:'var(--teal)',borderRadius:'50%',animation:'pulse 2s infinite'}}/> AI-Powered Healthcare OS",
  "        </div>",
  "        <h1 className='fu' style={{fontFamily:'Syne,sans-serif',fontSize:62,lineHeight:1.08,fontWeight:700,marginBottom:20,letterSpacing:-1}}>",
  "          Cut Wait Times By{' '}",
  "          <span style={{background:tg,WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'}}>70%</span>",
  "          {' '}with Smart Queuing",
  "        </h1>",
  "        <p className='fu' style={{fontSize:17,lineHeight:1.75,color:'var(--txt2)',marginBottom:36,maxWidth:540,margin:'0 auto 36px'}}>",
  "          MEDIQUEUE uses AI to predict, manage, and streamline patient flow — giving clinics world-class tools without the waiting room chaos.",
  "        </p>",
  "        <div className='fu' style={{display:'flex',gap:12,justifyContent:'center',flexWrap:'wrap'}}>",
  "          <button onClick={()=>nav('/login')} style={{padding:'14px 28px',background:tg,color:'#fff',border:'none',borderRadius:12,fontFamily:'DM Sans,sans-serif',fontSize:15,fontWeight:700,cursor:'pointer',boxShadow:'0 6px 20px rgba(13,155,130,.35)',display:'flex',alignItems:'center',gap:8}}>",
  "            <i className='fas fa-calendar-check'/> Book Appointment",
  "          </button>",
  "          <button onClick={()=>nav('/register')} style={{padding:'14px 28px',background:'transparent',color:'var(--txt)',border:'1.5px solid var(--bdr2)',borderRadius:12,fontFamily:'DM Sans,sans-serif',fontSize:15,fontWeight:600,cursor:'pointer',display:'flex',alignItems:'center',gap:8}}>",
  "            <i className='fas fa-user-plus'/> Create Account",
  "          </button>",
  "        </div>",
  "        <div style={{display:'flex',gap:28,justifyContent:'center',marginTop:32,fontSize:13,color:'var(--txt3)'}}>",
  "          {[['shield-check','#10B981','HIPAA Compliant'],['lock','#10B981','End-to-End Encrypted'],['star','#F59E0B','4.9 Rated']].map(([ic,c,l])=>(",
  "            <span key={l} style={{display:'flex',alignItems:'center',gap:5}}><i className={'fas fa-'+ic} style={{color:c}}/>{l}</span>",
  "          ))}",
  "        </div>",
  "      </div>",
  "      <div style={{background:'#0A1628',padding:'52px 40px'}}>",
  "        <div style={{maxWidth:1100,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:32,textAlign:'center'}}>",
  "          {[['500+','Partner Clinics'],['70%','Wait Time Reduction'],['2M+','Patients Served'],['4.9★','Average Rating']].map(([n,l])=>(",
  "            <div key={l}><div style={{fontFamily:'Syne,sans-serif',fontSize:44,fontWeight:700,background:tg,WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'}}>{n}</div><div style={{fontSize:13,color:'#94A3B8',marginTop:4}}>{l}</div></div>",
  "          ))}",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "}"
].join('\n'));

// ── src/pages/Dashboard.jsx
fs.writeFileSync('src/pages/Dashboard.jsx', [
  "import { useState, useEffect } from 'react';",
  "import { useAuth } from '../context/AuthContext';",
  "import { adminAPI, appointmentAPI, doctorAPI } from '../services/api';",
  "",
  "const tg = 'linear-gradient(135deg,#0D9B82,#1DBEA0)';",
  "",
  "function Sidebar({ role, active, onNav, user, onLogout }) {",
  "  const navs = {",
  "    patient: [",
  "      { id:'overview', icon:'fa-home', label:'Dashboard' },",
  "      { id:'appointments', icon:'fa-calendar-check', label:'Appointments' },",
  "      { id:'queue', icon:'fa-ticket-alt', label:'Queue Status' },",
  "      { id:'doctors', icon:'fa-user-md', label:'Find Doctors' },",
  "      { id:'settings', icon:'fa-cog', label:'Settings' }",
  "    ],",
  "    doctor: [",
  "      { id:'overview', icon:'fa-home', label:'Dashboard' },",
  "      { id:'queue', icon:'fa-ticket-alt', label:'Queue Mgmt' },",
  "      { id:'appointments', icon:'fa-calendar-alt', label:'Schedule' },",
  "      { id:'settings', icon:'fa-cog', label:'Settings' }",
  "    ],",
  "    admin: [",
  "      { id:'overview', icon:'fa-home', label:'Overview' },",
  "      { id:'appointments', icon:'fa-calendar-alt', label:'Appointments' },",
  "      { id:'doctors', icon:'fa-user-md', label:'Doctors' },",
  "      { id:'settings', icon:'fa-cog', label:'Settings' }",
  "    ]",
  "  };",
  "  return (",
  "    <aside style={{width:250,background:'var(--surf)',borderRight:'1px solid var(--bdr)',height:'100vh',display:'flex',flexDirection:'column',flexShrink:0}}>",
  "      <div style={{padding:'18px 14px',borderBottom:'1px solid var(--bdr)',display:'flex',alignItems:'center',gap:9}}>",
  "        <div style={{width:32,height:32,background:tg,borderRadius:9,display:'flex',alignItems:'center',justifyContent:'center'}}><i className='fas fa-heart-pulse' style={{color:'#fff',fontSize:14}}/></div>",
  "        <span style={{fontFamily:'Syne,sans-serif',fontWeight:700,fontSize:16,background:tg,WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'}}>MEDIQUEUE</span>",
  "      </div>",
  "      <div style={{flex:1,padding:'10px 8px',overflowY:'auto'}}>",
  "        {(navs[role]||navs.patient).map(item=>(",
  "          <div key={item.id} onClick={()=>onNav(item.id)} style={{display:'flex',alignItems:'center',gap:9,padding:'9px 11px',borderRadius:10,cursor:'pointer',marginBottom:2,background:active===item.id?'var(--tealXL)':'transparent',color:active===item.id?'var(--teal)':'var(--txt2)',fontWeight:active===item.id?600:500,fontSize:13,transition:'all .2s'}}>",
  "            <div style={{width:30,height:30,borderRadius:8,background:active===item.id?tg:'transparent',display:'flex',alignItems:'center',justifyContent:'center',fontSize:13,color:active===item.id?'#fff':'inherit'}}><i className={'fas '+item.icon}/></div>",
  "            {item.label}",
  "          </div>",
  "        ))}",
  "      </div>",
  "      <div style={{padding:'10px 8px',borderTop:'1px solid var(--bdr)'}}>",
  "        <div onClick={onLogout} style={{display:'flex',alignItems:'center',gap:9,padding:'9px 11px',borderRadius:10,cursor:'pointer',color:'var(--txt2)',fontSize:13}}>",
  "          <div style={{width:32,height:32,borderRadius:9,background:tg,display:'flex',alignItems:'center',justifyContent:'center',color:'#fff',fontWeight:700,fontSize:13,flexShrink:0}}>",
  "            {user?.name?.slice(0,2).toUpperCase()}",
  "          </div>",
  "          <div style={{flex:1}}><div style={{fontSize:12,fontWeight:600}}>{user?.name}</div><div style={{fontSize:10,color:'var(--txt3)',textTransform:'capitalize'}}>{user?.role}</div></div>",
  "          <i className='fas fa-sign-out-alt' style={{fontSize:13}}/>",
  "        </div>",
  "      </div>",
  "    </aside>",
  "  );",
  "}",
  "",
  "function MetricCard({ label, val, icon, color='#0D9B82', bg='#E6F7F4' }) {",
  "  return (",
  "    <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:'18px 20px',position:'relative',overflow:'hidden'}}>",
  "      <div style={{fontSize:11,fontWeight:700,color:'var(--txt3)',textTransform:'uppercase',letterSpacing:.6,marginBottom:7}}>{label}</div>",
  "      <div style={{fontFamily:'Syne,sans-serif',fontSize:28,fontWeight:700}}>{val}</div>",
  "      <div style={{position:'absolute',top:14,right:14,width:38,height:38,borderRadius:10,background:bg,display:'flex',alignItems:'center',justifyContent:'center',fontSize:16,color}}><i className={'fas fa-'+icon}/></div>",
  "    </div>",
  "  );",
  "}",
  "",
  "function OverviewPanel({ role }) {",
  "  const [stats, setStats] = useState(null);",
  "  const [appointments, setAppointments] = useState([]);",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    const load = async () => {",
  "      try {",
  "        if (role === 'admin') {",
  "          const r = await adminAPI.getStats();",
  "          setStats(r.data.stats);",
  "        }",
  "        const r2 = await appointmentAPI.getAll();",
  "        setAppointments(r2.data.appointments || []);",
  "      } catch(e) { console.error(e); }",
  "      finally { setLoading(false); }",
  "    };",
  "    load();",
  "  }, [role]);",
  "",
  "  if (loading) return <div style={{padding:40,color:'var(--txt2)',fontSize:14}}>Loading dashboard...</div>;",
  "",
  "  return (",
  "    <div className='fu'>",
  "      {role === 'admin' && stats && (",
  "        <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14,marginBottom:20}}>",
  "          <MetricCard label='Total Patients' val={stats.totalPatients} icon='users' color='#0D9B82' bg='#E6F7F4'/>",
  "          <MetricCard label='Active Doctors' val={stats.activeDoctors} icon='user-md' color='#7C3AED' bg='#EDE9FE'/>",
  "          <MetricCard label=\"Today's Appointments\" val={stats.todayAppointments} icon='calendar-check' color='#F59E0B' bg='#FEF3C7'/>",
  "          <MetricCard label='Queue Size' val={stats.currentQueueSize} icon='ticket-alt' color='#F43F5E' bg='#FFE4E6'/>",
  "        </div>",
  "      )}",
  "      {role === 'patient' && (",
  "        <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14,marginBottom:20}}>",
  "          <MetricCard label='My Appointments' val={appointments.length} icon='calendar-check' color='#0D9B82' bg='#E6F7F4'/>",
  "          <MetricCard label='Completed' val={appointments.filter(a=>a.status==='completed').length} icon='check-circle' color='#10B981' bg='#D1FAE5'/>",
  "          <MetricCard label='Upcoming' val={appointments.filter(a=>a.status==='confirmed').length} icon='clock' color='#F59E0B' bg='#FEF3C7'/>",
  "          <MetricCard label='Cancelled' val={appointments.filter(a=>a.status==='cancelled').length} icon='times-circle' color='#F43F5E' bg='#FFE4E6'/>",
  "        </div>",
  "      )}",
  "      {role === 'doctor' && (",
  "        <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14,marginBottom:20}}>",
  "          <MetricCard label=\"Today's Patients\" val={appointments.length} icon='users' color='#0D9B82' bg='#E6F7F4'/>",
  "          <MetricCard label='Confirmed' val={appointments.filter(a=>a.status==='confirmed').length} icon='calendar-check' color='#7C3AED' bg='#EDE9FE'/>",
  "          <MetricCard label='Completed' val={appointments.filter(a=>a.status==='completed').length} icon='check-circle' color='#10B981' bg='#D1FAE5'/>",
  "          <MetricCard label='Pending' val={appointments.filter(a=>a.status==='pending').length} icon='clock' color='#F59E0B' bg='#FEF3C7'/>",
  "        </div>",
  "      )}",
  "      <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:22}}>",
  "        <div style={{fontFamily:'Syne,sans-serif',fontSize:15,fontWeight:700,marginBottom:16}}>",
  "          {role === 'doctor' ? \"Today's Schedule\" : 'Recent Appointments'}",
  "        </div>",
  "        {appointments.length === 0 ? (",
  "          <div style={{textAlign:'center',padding:'32px 0',color:'var(--txt3)',fontSize:14}}>",
  "            <i className='fas fa-calendar' style={{fontSize:36,marginBottom:12,display:'block'}}/> No appointments yet",
  "          </div>",
  "        ) : (",
  "          <table style={{width:'100%',borderCollapse:'collapse'}}>",
  "            <thead><tr>{['Date & Time', role==='doctor'?'Patient':'Doctor', 'Type','Status'].map(h=>(",
  "              <th key={h} style={{fontSize:11,fontWeight:700,letterSpacing:.7,textTransform:'uppercase',color:'var(--txt3)',padding:'8px 12px',borderBottom:'1px solid var(--bdr)',textAlign:'left'}}>{h}</th>",
  "            ))}</tr></thead>",
  "            <tbody>{appointments.slice(0,8).map((a,i)=>(",
  "              <tr key={i} style={{borderBottom:'1px solid var(--bdr)'}}>",
  "                <td style={{padding:'11px 12px',fontSize:13}}>{new Date(a.appointment_time).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</td>",
  "                <td style={{padding:'11px 12px',fontSize:13,fontWeight:600}}>{role==='doctor'?a.patient_name:a.doctor_name}</td>",
  "                <td style={{padding:'11px 12px'}}><span style={{fontSize:11,padding:'3px 9px',borderRadius:99,fontWeight:700,background:a.type==='telehealth'?'#EDE9FE':'#DBEAFE',color:a.type==='telehealth'?'#5B21B6':'#1E40AF'}}>{a.type}</span></td>",
  "                <td style={{padding:'11px 12px'}}><span style={{fontSize:11,padding:'3px 9px',borderRadius:99,fontWeight:700,background:a.status==='confirmed'?'#D1FAE5':a.status==='completed'?'#E6F7F4':a.status==='cancelled'?'#FFE4E6':'#FEF3C7',color:a.status==='confirmed'?'#065F46':a.status==='completed'?'#0A7A67':a.status==='cancelled'?'#9F1239':'#92400E'}}>{a.status}</span></td>",
  "              </tr>",
  "            ))}</tbody>",
  "          </table>",
  "        )}",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  "",
  "function DoctorsPanel() {",
  "  const [doctors, setDoctors] = useState([]);",
  "  const [loading, setLoading] = useState(true);",
  "  useEffect(() => {",
  "    doctorAPI.getAll().then(r => setDoctors(r.data.doctors || [])).catch(console.error).finally(() => setLoading(false));",
  "  }, []);",
  "  if (loading) return <div style={{padding:40,color:'var(--txt2)',fontSize:14}}>Loading doctors...</div>;",
  "  return (",
  "    <div className='fu'>",
  "      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(210px,1fr))',gap:16}}>",
  "        {doctors.length === 0 ? (",
  "          <div style={{gridColumn:'1/-1',textAlign:'center',padding:48,color:'var(--txt3)',fontSize:14}}><i className='fas fa-user-md' style={{fontSize:40,display:'block',marginBottom:12}}/>No doctors found</div>",
  "        ) : doctors.map(d => (",
  "          <div key={d.id} style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:22,textAlign:'center',transition:'all .2s'}}>",
  "            <div style={{width:64,height:64,borderRadius:16,background:tg,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:700,fontSize:22,color:'#fff',margin:'0 auto 12px'}}>",
  "              {d.name?.slice(0,2).toUpperCase()}",
  "            </div>",
  "            <div style={{fontWeight:700,fontSize:14,marginBottom:3}}>{d.name}</div>",
  "            <div style={{color:'var(--txt3)',fontSize:12,marginBottom:10}}>{d.speciality}</div>",
  "            <div style={{color:'#F59E0B',fontSize:12,marginBottom:12}}>★ {d.rating} · {d.experience_years} yrs exp</div>",
  "            <div style={{fontSize:13,fontWeight:700,color:'var(--teal)',marginBottom:14}}>₹{d.consultation_fee}</div>",
  "            <button style={{width:'100%',padding:'9px',background:tg,color:'#fff',border:'none',borderRadius:9,fontFamily:'DM Sans,sans-serif',fontSize:12,fontWeight:700,cursor:'pointer'}}>Book Appointment</button>",
  "          </div>",
  "        ))}",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  "",
  "function SettingsPanel({ user }) {",
  "  return (",
  "    <div className='fu' style={{maxWidth:500}}>",
  "      <div style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:28}}>",
  "        <div style={{fontFamily:'Syne,sans-serif',fontSize:15,fontWeight:700,marginBottom:20}}>Account Details</div>",
  "        {[['Full Name',user?.name],['Email',user?.email],['Role',user?.role]].map(([l,v])=>(",
  "          <div key={l} style={{marginBottom:16}}>",
  "            <label style={{display:'block',fontSize:12,fontWeight:700,color:'var(--txt2)',marginBottom:5,textTransform:'uppercase',letterSpacing:.4}}>{l}</label>",
  "            <input defaultValue={v} readOnly style={{width:'100%',padding:'11px 14px',background:'var(--surf2)',border:'1.5px solid var(--bdr)',borderRadius:10,fontSize:13,color:'var(--txt)',outline:'none'}}/>",
  "          </div>",
  "        ))}",
  "        <div style={{padding:'12px 14px',background:'var(--tealXL)',borderRadius:10,fontSize:13,color:'var(--tealDk)'}}>",
  "          <i className='fas fa-info-circle' style={{marginRight:7}}/>Connected to live PostgreSQL database",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  "",
  "export default function Dashboard() {",
  "  const { user, logout } = useAuth();",
  "  const [panel, setPanel] = useState('overview');",
  "  const titles = { overview:'Dashboard', appointments:'Appointments', queue:'Queue Status', doctors:'Find Doctors', settings:'Settings' };",
  "",
  "  const renderPanel = () => {",
  "    switch(panel) {",
  "      case 'overview': return <OverviewPanel role={user?.role}/>;",
  "      case 'doctors': return <DoctorsPanel/>;",
  "      case 'settings': return <SettingsPanel user={user}/>;",
  "      default: return (",
  "        <div className='fu' style={{background:'var(--surf)',border:'1px solid var(--bdr)',borderRadius:16,padding:48,textAlign:'center'}}>",
  "          <i className='fas fa-tools' style={{fontSize:40,color:'var(--txt3)',display:'block',marginBottom:14}}/>",
  "          <div style={{fontFamily:'Syne,sans-serif',fontSize:17,fontWeight:700,marginBottom:8}}>{titles[panel]}</div>",
  "          <div style={{color:'var(--txt2)',fontSize:13}}>This panel connects to your live backend. Phase 4 will add full UI.</div>",
  "        </div>",
  "      );",
  "    }",
  "  };",
  "",
  "  return (",
  "    <div style={{display:'flex',height:'100vh',overflow:'hidden'}}>",
  "      <Sidebar role={user?.role} active={panel} onNav={setPanel} user={user} onLogout={logout}/>",
  "      <div style={{flex:1,display:'flex',flexDirection:'column',overflow:'hidden'}}>",
  "        <div style={{height:62,padding:'0 24px',display:'flex',alignItems:'center',justifyContent:'space-between',background:'var(--surf)',borderBottom:'1px solid var(--bdr)',flexShrink:0}}>",
  "          <div>",
  "            <div style={{fontFamily:'Syne,sans-serif',fontSize:18,fontWeight:700}}>{titles[panel]||panel}</div>",
  "            <div style={{fontSize:11,color:'var(--txt3)'}}>Welcome back, {user?.name}!</div>",
  "          </div>",
  "          <div style={{display:'flex',alignItems:'center',gap:10}}>",
  "            <span style={{fontSize:12,padding:'4px 12px',borderRadius:99,fontWeight:700,background:'#E6F7F4',color:'#0A7A67',textTransform:'capitalize'}}>{user?.role}</span>",
  "            <div style={{width:36,height:36,borderRadius:9,background:tg,display:'flex',alignItems:'center',justifyContent:'center',color:'#fff',fontWeight:700,fontSize:13}}>{user?.name?.slice(0,2).toUpperCase()}</div>",
  "          </div>",
  "        </div>",
  "        <div style={{flex:1,overflowY:'auto',padding:24}} key={panel}>",
  "          {renderPanel()}",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "}"
].join('\n'));

console.log('');
console.log('✅ ALL FRONTEND FILES WRITTEN!');
console.log('');